/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author sarasb
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLogin = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jtxUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jPin = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to NCI Bank");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 410, 47);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 20, 0, 0);

        jLogin.setText("Login");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin);
        jLogin.setBounds(120, 320, 100, 40);

        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });
        getContentPane().add(jClear);
        jClear.setBounds(310, 320, 100, 40);

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit);
        jExit.setBounds(220, 390, 90, 30);

        jtxUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxUserName.setText("Username");
        getContentPane().add(jtxUserName);
        jtxUserName.setBounds(80, 150, 100, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 220, 90, 17);

        jtxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtUserName);
        jtxtUserName.setBounds(300, 150, 140, 30);

        jPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPinActionPerformed(evt);
            }
        });
        getContentPane().add(jPin);
        jPin.setBounds(300, 210, 140, 30);

        jLabel2.setText(" Please Enter Your details to Proceed");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 90, 260, 39);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/met2.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 510, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserNameActionPerformed

    private void jPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPinActionPerformed

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        
        String password = jPin.getText();
        String username = jtxtUserName.getText();
        
        if (password.contains("1001") && (username.contains("Sean")))
        {
            jtxtUserName.setText(null);
            jPin.setText(null);
             systemExit();
            
            NciAtm3 Info = new NciAtm3();
            Info.setVisible(true);
              this.setVisible(false);
        }
        if (password.contains("1002") && (username.contains("Athanasos")))
            {
            jtxtUserName.setText(null);
            jPin.setText(null);
             systemExit();
            
            NciAtm2 Info = new NciAtm2();
            Info.setVisible(true);
            this.setVisible(false);
        }
        if (password.contains("1003") && (username.contains("Almoruf")))
            {
            jtxtUserName.setText(null);
            jPin.setText(null);
            systemExit();
            
            NciAtm Info = new NciAtm();
            Info.setVisible(true);
            this.setVisible(false);
        }
          if (password.contains("1004") && (username.contains("Luke")))
            {
            jtxtUserName.setText(null);
            jPin.setText(null);
         
            
         
            NciAtm1 Info = new NciAtm1();
            Info.setVisible(true);
            this.setVisible(false);
            
        }
        
    }//GEN-LAST:event_jLoginActionPerformed
    //This code performs exit action
    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jExitActionPerformed
    //This code performs clear username and password field
    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        jtxtUserName.setText(null);
        jPin.setText(null);
    }//GEN-LAST:event_jClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jClear;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLogin;
    private javax.swing.JPasswordField jPin;
    private javax.swing.JLabel jtxUserName;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables
private void systemExit()
{
WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}
}






